### ISSUE TITLE
Reuse existing parsing/linting libraries 

### ISSUE THREAD

**Issue by roman01la** [snoe/clojure-lsp#66] opened 2019-08-22 21:55 UTC
So I was spending an evening implementing invalid arity diagnostic and wondering if it would make sense to use existing libraries for linting. My original concern was about double parsing, once by lsp and once by linting library, but clj-kondo https://github.com/borkdude/clj-kondo seem to provide analysis data which could be reused in lsp. The library seems to have lots of linting rules. @snoe what do you think?

**Comment by snoe** [comment] 2019-08-23 13:32
Yup, this is somewhat a dupe of #36 - I looked at the kondo parsing very briefly and I think there might be some information we would need added. There was effort a little while ago https://github.com/benedekfazekas/trin that was trying to unify this analysis into a library but seems to have stalled. If you or someone else sees a path to build lsp off of the kondo parsing or vice versa or through a common library, give it a shot. 

I think the main things we need are accurate row/col positions, fully qualified symbols - including a sense of scope for e.g. `let` vars, knowledge of aliases across the project, and the ability to search the parsed results. Our macro-defs might need to be in there, or could potentially be done in a second step, but I think declarations that can statically understand user macros that introduce new vars is quite important.

**Comment by Cnly** [comment] 2020-01-21 08:09
I'm doing some experiments to integrate clj-kondo on my branch: https://github.com/Cnly/clojure-lsp/tree/clj-kondo-integration. Basically I was able to replace most of the diagnostics functionalities with clj-kondo, but also needed to beautify results from clj-kondo using references that clojure-lsp found, because clj-kondo provides only the starting position (not a range) for its diagnostics items.

For the same reason, I think it's not enough to use clj-kondo for all the parsing, or functions like `find-reference-under-cursor` may not work.

And if this is desirable perhaps I could work on it more and open a PR?

**Comment by snoe** [comment] 2020-01-21 14:25
I think it might be worthwhile to reach out to kondo and see if they can expose end ranges. They have an lsp client too so I figure it should be possible.

**Comment by snoe** [comment] 2020-01-21 23:48
@Cnly this seems to be the relevant kondo.lsp range https://github.com/borkdude/clj-kondo.lsp/blob/master/server/src/clj_kondo/lsp_server/impl/server.clj#L72-L73

cc @borkdude Is there a facility in kondo to get proper ranges for diagnostics that maybe we're missing?  Would it be worthwhile pursuing that inside kondo or should we do the cross referencing that @Cnly was suggesting?

**Comment by snoe** [comment] 2020-01-21 23:50
Oh and something I should add from my first comment, is that @borkdude did convince me that we should be ok parsing twice and we shouldn't let that hold up kondo integration.

**Comment by borkdude** [comment] 2020-01-22 08:37
Currently clj-kondo does not expose ranges, but only the start row and col. This is because initially we only supported flycheck etc. which do not have the concept of ranges. Later we added an LSP-server to support VSCode, IntelliJ and now also Emacs. 

Nobody has been asking for ranges yet, since just providing the start position seems sufficient for all of these three editors. It will be an official part of the LSP protocol that when the start position is the same as the end position, the editor will highlight the entire token at that position.

VSCode:
https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md#clj-kondo-extension

Emacs:
https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md#lsp-server

IntelliJ:
https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md#lsp-server-1

Can you explain to me why only exposing the start position is not sufficient? Theoretically these could be added, but as already 3 editors work fine with it, I'm not sure if it's worth the effort?

**Comment by snoe** [comment] 2020-01-24 03:54
No, that sounds great. I didn't realize that would work. @Cnly I'd love to know if that's sufficient to get Kondo diagnostics on your branch using this trick.

**Comment by Cnly** [comment] 2020-01-26 04:25
Good to know, thanks. If that behaviour is still not part of the spec, maybe it's still preferable to beautify the results ourselves? At least coc.nvim doesn't have that behaviour yet according to my tests. Also I think my branch is already a working version; it's just that I need to fix the tests.

**Comment by borkdude** [comment] 2020-01-26 08:44
@Cnly I was just reading how you did this. If this is performant, that seems ok:

https://github.com/Cnly/clojure-lsp/commit/54515b0efd334a1c2d8e2b1e57bb1d2a413b4487#diff-36311287db83beb7cd1e00b298eb8985R160

Two questions:

Is `usages` a complete list of all tokens from the code, i.e. will this code always be able to resolve the end row and column?

For performance it may be better to index usages by row and col, to be able to find the end row and col faster?

**Comment by borkdude** [comment] 2020-01-26 10:47
Meanwhile I'll see what I can do in clj-kondo itself: https://github.com/borkdude/clj-kondo/issues/711

**Comment by Cnly** [comment] 2020-01-26 14:22
@borkdude 

> Is usages a complete list of all tokens from the code, i.e. will this code always be able to resolve the end row and column?

`usages` is supposed to be a complete list. In case the end row and column aren't found in there (e.g. when kondo gives a position of a `(` character), end row and column will be the same as the starts - that's why I used `merge`.

> For performance it may be better to index usages by row and col, to be able to find the end row and col faster?

Yes, that's probably going to speed up the process. But clojure-lsp currently doesn't do that now, so :/

> Meanwhile I'll see what I can do in clj-kondo itself: borkdude/clj-kondo#711

Thanks! 😄 By the way, is clj-kondo.lsp able to work across namespaces? I think I'm having some problems fixing tests involving diagnostics for `require`-ed symbols.

**Comment by borkdude** [comment] 2020-01-26 15:04
@Cnly Can you test with the new version from master?

```
$ clojure -Sdeps '{:deps {clj-kondo {:mvn/version "2020.01.14-20200126.145730-7"}}}' -m clj-kondo.main --lint - --config '{:output {:format :edn}}' <<< '(inc)'

{:findings [{:filename "<stdin>", :row 1, :end-row 1, :col 1, :end-col 6, :level :error, :type :invalid-arity, :message "clojure.core/inc is called with 0 args but expects 1"}], :summary {:error 1, :warning 0, :info 0, :type :summary, :duration 45}}
```

Notice the addition of `:end-row` and `:end-col`.

**Comment by borkdude** [comment] 2020-01-26 15:10
>  By the way, is clj-kondo.lsp able to work across namespaces?

Note sure what you mean here, but if that's a different issue with clj-kondo not related to this issue, I suggest creating an issue for this at clj-kondo or come chat in the clj-kondo channel on Clojurians slack.

**Comment by borkdude** [comment] 2020-01-26 15:31
I tested this with VSCode:

![Screenshot 2020-01-26 16 30 44](https://user-images.githubusercontent.com/284934/73137514-3c877a00-4059-11ea-991d-c82836171142.png)

I had to change the following bit of code in clj-kondo.lsp:

```
(defn finding->Diagnostic [{:keys [:row :col :end-row :end-col :message :level]}]
  (let [row (max 0 (dec row))
        col (max 0 (dec col))
        end-row (max 0 (dec end-row))
        end-col (max 0 (dec end-col))]
    (Diagnostic. (Range. (Position. row col)
                         (Position. end-row end-col))
                 message
                 (case level
                   :info DiagnosticSeverity/Information
                   :warning DiagnosticSeverity/Warning
                   :error DiagnosticSeverity/Error)
                 "clj-kondo")))
```

**Comment by Cnly** [comment] 2020-01-26 15:33
@borkdude Just tested the new version. Can confirm end-row and end-col are working. Perhaps just one thing: for an unused function, the end position goes all the way to the end of the function definition, and all those lines are underlined by the LSP client. Maybe just give the range of the `defn` line for this case?

**Comment by borkdude** [comment] 2020-01-26 16:11
@Cnly Done. Tested with IntelliJ:

![Screenshot 2020-01-26 17 04 21](https://user-images.githubusercontent.com/284934/73138004-35169f80-405e-11ea-89c5-0fd9d91ab1d6.png)

**Comment by Cnly** [comment] 2020-01-26 17:59
@borkdude Can confirm. And I found another case: `Redundant do`. Is it possible to have a unified fix for the like?

**Comment by borkdude** [comment] 2020-01-26 18:53
@Cnly A workaround for this could be in the LSP server implementation:

``` clojure
(defn finding->Diagnostic [lines {:keys [:row :col :end-row :end-col :message :level]}]
  (let [row (max 0 (dec row))
        col (max 0 (dec col))
        start-char (when-let [^String line (nth lines row)]
                     (.charAt line col))
        expression? (identical? \( start-char)
        end-row (cond expression? row
                      end-row (max 0 (dec end-row))
                      :else row)
        end-col (cond expression? (inc col)
                      end-col (max 0 (dec end-col))
                      :else col)]
    (Diagnostic. (Range. (Position. row col)
                         (Position. end-row end-col))
                 message
                 (case level
                   :info DiagnosticSeverity/Information
                   :warning DiagnosticSeverity/Warning
                   :error DiagnosticSeverity/Error)
                 "clj-kondo")))

(defn uri->lang [uri]
  (when-let [dot-idx (str/last-index-of uri ".")]
    (let [ext (subs uri (inc dot-idx))
          lang (keyword ext)]
      (if (contains? #{:clj :cljs :cljc :edn} lang)
        lang
        :clj))))

(defn lint! [text uri]
  (let [lang (uri->lang uri)
        {:keys [:findings]} (with-in-str text (clj-kondo/run! {:lint ["-"]
                                                               :lang lang}))
        lines (str/split text #"\r?\n")]
    (.publishDiagnostics ^LanguageClient @proxy-state
                         (PublishDiagnosticsParams.
                          uri
                          (map #(finding->Diagnostic lines %) findings)))))
```

So we just check if the character at the start is an opening paren and if so, we only highlight the expression?

**Comment by borkdude** [comment] 2020-01-26 19:32
Pushed one fix for the region of unresolved symbols.

**Comment by Cnly** [comment] 2020-01-27 09:08
@borkdude Yeah, that's a plausible way to do it.

**Comment by borkdude** [comment] 2020-01-27 09:10
@Cnly If there are no other problems, then I'll release this so we can get on with this issue. Do you need more time or can I go ahead?

**Comment by Cnly** [comment] 2020-01-27 09:16
@borkdude I think we're good to go. Thank you so much for working on this! :)

**Comment by borkdude** [comment] 2020-01-27 10:05
@Cnly I just bumped the version to `2020.01.27` which should be available on clojars in the coming hour. I'll make a release of the new binary and LSP server later.

**Comment by snoe** [comment] 2020-01-27 17:53
@Cnly How does you branch/kondo interact with diagnostics from macro-defs?

I wonder if we should/need to add a `:tag` to `macro-def`'d `usages` that falls back to the clojure-lsp diagnostics for those places where kondo's `lint-as` falls short. 

I'm thinking in particular about the recent work @Luminiscental did with `multi-arity` diagnostics  and schema.core but I might have some other examples of macros we use at work that wouldn't make sense to add explicit support for.

https://github.com/snoe/clojure-lsp/issues/104
https://github.com/snoe/clojure-lsp/issues/108

**Comment by Luminiscental** [comment] 2020-01-27 18:15
At least with the schema.core stuff I'm pretty sure kondo supports it fine already, but maybe there are other places where having such a tag could be useful.

**Comment by borkdude** [comment] 2020-01-27 19:08
FWIW: clj-kondo has built-in support for schema.core.

**Comment by Cnly** [comment] 2020-02-03 17:34
@snoe Currently kondo's `lint-as` is not used so clojure-lsp is still responsible for those custom macros. Additionally, the way kondo is integrated now (passing the current file content when changed to `kondo/run!`, same as what clj-kondo.lsp does) doesn't give it workspace visibility, so it seems clojure-lsp will also be responsible for linting referred symbols, etc.

**Comment by borkdude** [comment] 2020-02-18 11:04
I think there are two ways of looking at integrating clj-kondo:

1) Integrate it as is, so users don't have to install anything else (the binary, etc). Users should not expect the behavior to be different than when using clj-kondo via flycheck, etc. They should just configure their .clj-kondo/config.edn as usual. 

2) Integrate clj-kondo and try to improve upon its results (false positive unresolved symbols in macros for example) using other information already in clojure-lsp.

The Calva plugin for VSCode has chosen option 1. If clojure-lsp would also make that choice, it should maybe have the option to disable clj-kondo in clojure-lsp when users don't want it. In VSCode / Calva that just means disabling the clj-kondo extension.

**Comment by borkdude** [comment] 2020-02-19 12:58
I just learned about this tool https://github.com/nedap/formatting-stack which also combines various linters into one experience.

**Comment by ericdallo** [comment] 2020-07-26 21:26
@snoe and @Cnly I think this issue lost somewhere, I really think we should use the @Cnly branch using `clj-kondo`, what's missing? I think we can use as it is like @borkdude said and address the issues on other PRs.

**Comment by snoe** [comment] 2020-07-27 14:32
@ericdallo The hooks in kondo I think now are able to completely replace the macrodefs and are available in kondo's analyzer. 

What I would like is: 
1. merge this (with newest kondo) to replace our diagnostics
2. Figure out if kondo's analyzer can replace our parser.clj and db `usages`. Refactorings/Transformations would still need to be handled by lsp, but the bulk, I think, can just be kondo. I think even if we lose some functionality with this switch, working to improve kondo's analysis instead of lsp's will be a better path forward for clojure as a whole.

**Comment by ericdallo** [comment] 2020-07-27 14:36
I totally agree with that @snoe!
Maybe @Cnly can rebase with master its branch?

**Comment by Cnly** [comment] 2020-07-27 15:11
This is getting a bit old. I remember one big issue I had to think about back then was that kondo can't lint across files, but yes we can still replace the majority of linting with kondo and try to improve that. I can take some time recently to look at this again. :)

**Comment by ericdallo** [comment] 2020-07-27 15:17
Thank you @Cnly!
What do you mean with "Kondo can't lint across files"?

**Comment by Cnly** [comment] 2020-07-28 06:02
@ericdallo It means kondo integrates in LSP servers now mainly by taking the content of each file to lint, rather than analysing a bunch of files. For example see the reference implementation: https://github.com/borkdude/clj-kondo.lsp/blob/66a54966d8e5b26643e9b39241ba26c1215f5f9d/server/src/clj_kondo/lsp_server/impl/server.clj#L120-L124. This way kondo won't be able to know symbols defined in another file, etc.

**Comment by ericdallo** [comment] 2020-07-28 12:32
Oh @Cnly this is kind of a problem, right?

This is one of the greatest features of a LSP IMO :/

@borkdude is there any way to achieve that?

**Comment by borkdude** [comment] 2020-07-28 13:48
The way this works normally with clj-kondo is:

- User have a `.clj-kondo` directory in the root of their project. Clj-kondo automatically saves information into this directory under `.clj-kondo/cache`.
- As the users edits files, more and more information comes available.
- If you want to make the information available beforehand, you can lint your entire classpath our source dirs with `clj-kondo --lint $(clojure -Spath)` or `clj-kondo --lint src test`.

**Comment by ericdallo** [comment] 2020-07-28 13:59
I see, do you see any problem `clojure-lsp` do `clj-kondo --lint <classpaths>` on LSP start? 
Currently, `clojure-lsp` already analyses all references so I think this would not be a bigger problem

**Comment by borkdude** [comment] 2020-07-28 14:00
I don't see a problem other than that it can take a while, depending on the amount of dependencies. The linting can also be done programmatically, using the `clj-kondo.core` namespace.

**Comment by ericdallo** [comment] 2020-07-28 14:21
Yes, I agree, we can test the performance compared with how `clojure-lsp` do that currently, WDYT @Cnly?

**Comment by Cnly** [comment] 2020-08-02 13:09
That's great! It didn't occur to me that I can also pass directories or the classpath programatically. Let me see how I can pick up my old branch. :)

**Closed** 2020-08-05 20:41 UTC
